services:
  php:
    image: tugboatqa/php:7.4-apache
    default: true
    alias_type: domain
    aliases:
      - demo.backdropcms.org
    depends: mariadb
    commands:
      init:
        # Configure PHP settings. Note the file renaming.
        - cp $TUGBOAT_ROOT/.tugboat/php.ini /usr/local/etc/php/conf.d/backdrop-php.ini
        # Install PHP 'zip' extension to allow installing Backdrop modules.
        - docker-php-ext-install zip opcache
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite expires headers
        # Download Backdrop core.
        - cd $TUGBOAT_ROOT && wget https://github.com/backdrop/backdrop/releases/latest/download/backdrop.zip
        - cd $TUGBOAT_ROOT && unzip backdrop.zip && rm backdrop.zip
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT/backdrop $DOCROOT
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/backdrop/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/backdrop/settings.local.php
        # Create the config directories.
        - mkdir $TUGBOAT_ROOT/backdrop/files/config
        - mkdir $TUGBOAT_ROOT/backdrop/files/config/active
        - mkdir $TUGBOAT_ROOT/backdrop/files/config/staging
      update:
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data $TUGBOAT_ROOT/backdrop
        - find $TUGBOAT_ROOT/backdrop/files $TUGBOAT_ROOT/backdrop/layouts $TUGBOAT_ROOT/backdrop/modules $TUGBOAT_ROOT/backdrop/themes -type d -exec chmod 2775 {} \;
        - find $TUGBOAT_ROOT/backdrop/files $TUGBOAT_ROOT/backdrop/layouts $TUGBOAT_ROOT/backdrop/modules $TUGBOAT_ROOT/backdrop/themes -type f -exec chmod 0664 {} \;
        # Clear out active config (needed when rebuilding/reinstalling).
        - find $TUGBOAT_ROOT/backdrop/files/config/active -mindepth 1 -delete
        # Install Backdrop.
        - cd $TUGBOAT_ROOT/backdrop && php ./core/scripts/install.sh --db-url=mysql://tugboat:tugboat@mariadb/tugboat --account-pass=password
        # Fix config permissions after install.
        - chown -R www-data:www-data $TUGBOAT_ROOT/backdrop/files/config/active
        - find $TUGBOAT_ROOT/backdrop/files/config/active -type f -exec chmod 0664 {} \;
      build:
        # Generate and display a login URL.
        - cd $TUGBOAT_ROOT/backdrop && ../.tugboat/auto-login.sh
  mariadb:
    image: tugboatqa/mariadb:10.7
    commands:
      init:
        # Configure database for UTF-8: https://api.backdropcms.org/database-configuration#utf8mb4
        - echo "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true" >> /etc/mysql/conf.d/utf8mb.conf
      update:
        # Drop and re-create the database (needed when rebuilding/reinstalling).
        - mysqladmin -f drop tugboat && mysqladmin create tugboat
